name: Deployment

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v1
      with:
        java-version: 16
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Add Arc release
      run: |
        git clone --depth=1 --branch=master https://github.com/WilloIzCitron/Arc ../Arc
        cd ../Arc
        git tag ${RELEASE_VERSION}
        git push https://WilloIzCitron:${{ secrets.API_TOKEN_GITHUB }}@github.com/WilloIzCitron/Arc ${RELEASE_VERSION};
        cd ../Genshindustry
    - name: Create artifacts
      run: |
        ./gradlew desktop:dist server:dist core:mergedJavadoc -Pbuildversion=${RELEASE_VERSION:1}
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Update F-Droid build string
      run: |
        git clone --depth=1 --branch=master https://github.com/WilloIzCitron/GenshindustryBuilds ../GenshindustryBuilds
        cd ../GenshindustryBuilds
        echo "Updating version to ${RELEASE_VERSION:1}"
        BNUM=$(($GITHUB_RUN_NUMBER + 1000))
        echo versionName=7-fdroid-${RELEASE_VERSION:1}$'\n'versionCode=${BNUM} > version_fdroid.txt
        git add .
        git commit -m "Updating to build ${RELEASE_VERSION:1}"
        git push https://WilloIzCitron:${{ secrets.API_TOKEN_GITHUB }}@github.com/WilloIzCitron/GenshindustryBuilds
        cd ../Genshindustry
    - name: Upload client artifacts
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: desktop/build/libs/Mindustry.jar
        tag: ${{ github.ref }}
    - name: Upload server artifacts
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: server/build/libs/server-release.jar
        tag: ${{ github.ref }}

