name: Tests

on: [push, workflow_dispatch]

jobs:
  runPush:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Trigger BE build
      if: ${{ github.repository == 'WilloIzCitron/Genshindustry' }}
      run: |
        git clone --depth=1 --branch=master https://github.com/WilloIzCitron/GenshindustryBuilds ../GenshindustryBuilds
        cd ../GenshindustryBuilds
        BNUM=$(($GITHUB_RUN_NUMBER + 20000))
        git tag ${BNUM}
        git config --global user.name "Github Actions"
        git push https://WilloIzCitron:${{ secrets.API_TOKEN_GITHUB }}@github.com/WilloIzCitron/GenshindustryBuilds ${BNUM}
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Update bundles
      if: ${{ github.repository == 'WilloIzCitron/Genshindustry' }}
      run: |
        ./gradlew updateBundles

        if [ -n "$(git status --porcelain)" ]; then
          git add core/assets/bundles/*
          git commit -m "Automatic bundle update"
          git push
        fi
    - name: Run unit tests
      run: ./gradlew clean cleanTest test --stacktrace
